endpoint: wss://bifrost-parachain.api.onfinality.io/public-ws
mock-signature-host: true
block: ${env.BIFROST_BLOCK_NUMBER}
db: ./db.sqlite

import-storage:
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000
