endpoint: wss://composable.api.onfinality.io/public-ws
mock-signature-host: true
block: ${env.COMPOSABLE_BLOCK_NUMBER}
db: ./composable.polkadot.db.sqlite
# wasm-override: ../../ComposableFi/composable/result/lib/runtime.optimized.wasm

import-storage:
  Sudo:
    Key: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY # Alice
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - data:
            free: "100000000000000000000000"
