endpoint:
  - wss://rpc.laos.laosfoundation.io
  - wss://laos-rpc.dwellir.com
db: ./db.sqlite
runtime-log-level: 5

import-storage:
    Sudo:
        Key: "0xf24FF3a9CF04c71Dbc94D0b566f7A27B94566cac" # Alith
    System:
        Account:
            - - - "0xf24FF3a9CF04c71Dbc94D0b566f7A27B94566cac"
              - providers: 1
                data:
                    free: "100000000000000000000000"
